FeatureTracker/FeatureTracker/Controllers/ConfigurationController.cs
using Microsoft.AspNetCore.Mvc;

namespace FeatureTracker.Controllers
{
    public class ConfigurationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FeatureTracker/FeatureTracker/Controllers/FeatureStatusController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FeatureTracker.Models;

namespace FeatureTracker.Controllers
{
    public class FeatureStatusController : Controller
    {
        private readonly FeatureTrackerContext _context;

        public FeatureStatusController(FeatureTrackerContext context)
        {
            _context = context;
        }

        // GET: Configuration/FeatureStatus
        [HttpGet("Configuration/FeatureStatus")]
        public async Task<IActionResult> Index()
        {
            var featureTrackerContext = _context.FeatureStatus
                                            .Include(f => f.LastUpdateUser)
                                            .Where(f => f.Deleted != true);

            return View(await featureTrackerContext.ToListAsync());
        }

        // GET: Configuration/FeatureStatus/Create
        [HttpGet("Configuration/FeatureStatus/Create")]
        public IActionResult Create()
        {
            ViewData["LastUpdateUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName");
            return View();
        }

        // POST: Configuration/FeatureStatus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("Configuration/FeatureStatus/Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FeatureStatusId,Name,LastUpdateUserId,Deleted")] FeatureStatus featureStatus)
        {
            if (ModelState.IsValid)
            {
                featureStatus.LastUpdateUserId = 1; // TODO change to current user
                featureStatus.Deleted = false;

                _context.Add(featureStatus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LastUpdateUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", featureStatus.LastUpdateUserId);
            return View(featureStatus);
        }

        // GET: Configuration/FeatureStatus/Edit/5
        [HttpGet("Configuration/FeatureStatus/Edit/{id?}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var featureStatus = await _context.FeatureStatus.FindAsync(id);
            if (featureStatus == null)
            {
                return NotFound();
            }
            ViewData["LastUpdateUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", featureStatus.LastUpdateUserId);
            return View(featureStatus);
        }

        // POST: Configuration/FeatureStatus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("Configuration/FeatureStatus/Edit/{id?}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FeatureStatusId,Name,LastUpdateUserId,Deleted")] FeatureStatus featureStatus)
        {
            return await EditUtility(id, featureStatus, false);
        }

        // GET: Configuration/FeatureStatus/Delete/5
        [HttpGet("Configuration/FeatureStatus/Delete/{id?}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var featureStatus = await _context.FeatureStatus
                .Include(f => f.LastUpdateUser)
                .FirstOrDefaultAsync(m => m.FeatureStatusId == id);
            if (featureStatus == null)
            {
                return NotFound();
            }

            return View(featureStatus);
        }

        // POST: Configuration/FeatureStatus/Delete/5
        [HttpPost("Configuration/FeatureStatus/Delete/{id?}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, [Bind("FeatureStatusId,Name,LastUpdateUserId,Deleted")] FeatureStatus featureStatus)
        {
            return await EditUtility(id, featureStatus, true);
        }

        private bool FeatureStatusExists(int id)
        {
            return _context.FeatureStatus.Any(e => e.FeatureStatusId == id);
        }

        private async Task<IActionResult> EditUtility(int id, [Bind("FeatureStatusId,Name,LastUpdateUserId,Deleted")] FeatureStatus featureStatus, bool deleting)
        {
            if (id != featureStatus.FeatureStatusId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (deleting)
                        featureStatus.Deleted = true;

                    featureStatus.LastUpdateUserId = 1; // TODO change to current user;

                    _context.Update(featureStatus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeatureStatusExists(featureStatus.FeatureStatusId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LastUpdateUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", featureStatus.LastUpdateUserId);
            return View(featureStatus);
        }

    }
}

FeatureTracker/FeatureTracker/Controllers/FeaturesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FeatureTracker.Models;
using System;

namespace FeatureTracker.Controllers
{
    public class FeaturesController : Controller
    {
        private readonly FeatureTrackerContext _context;

        public FeaturesController(FeatureTrackerContext context)
        {
            _context = context;
        }

        // GET: Features
        public async Task<IActionResult> Index()
        {
            var featureTrackerContext = _context.Feature
                                            .Include(f => f.AssigneeUser)
                                            .Include(f => f.FeatureCategory)
                                            .Include(f => f.FeatureStatus)
                                            .Include(f => f.LastUpdateUser)
                                            .Include(f => f.ReporterUser)
                                            .Where(f => f.Deleted != true);

            return View(await featureTrackerContext.ToListAsync());
        }

        // GET: Features/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feature = await _context.Feature
                .Include(f => f.AssigneeUser)
                .Include(f => f.FeatureCategory)
                .Include(f => f.FeatureStatus)
                .Include(f => f.LastUpdateUser)
                .Include(f => f.ReporterUser)
                .FirstOrDefaultAsync(m => m.FeatureId == id);

            var featureComment = await _context.FeatureComment
                .Where(fc => fc.FeatureId == id)
                .OrderBy(fc => fc.CreationDate)
                .ToListAsync();

            if (feature == null || featureComment == null)
            {
                return NotFound();
            }
            
            return View(new FeatureViewModel(feature, featureComment));
        }

        // GET: Features/Create
        public IActionResult Create()
        {
            ViewData["AssigneeUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName");
            ViewData["FeatureCategoryId"] = new SelectList(_context.Set<FeatureCategory>(), "FeatureCategoryId", "Name");
            ViewData["FeatureStatusId"] = new SelectList(_context.Set<FeatureStatus>(), "FeatureStatusId", "Name");
            ViewData["LastUpdateUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName");
            ViewData["ReporterUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName");

            return View();
        }

        // POST: Features/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FeatureId,ReporterUserId,AssigneeUserId,Title,Description,FeatureCategoryId,FeatureStatusId,CreationDate,UpdatedDate,LastUpdateUserId,Deleted")] Feature feature)
        {
            if (ModelState.IsValid)
            {
                feature.ReporterUserId = 1; // TODO set as current user
                feature.CreationDate = DateTime.Now;
                feature.UpdatedDate = DateTime.Now;
                feature.LastUpdateUserId = 1; // TODO set as current user
                feature.Deleted = false;

                _context.Add(feature);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["AssigneeUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", feature.AssigneeUserId);
            ViewData["FeatureCategoryId"] = new SelectList(_context.Set<FeatureCategory>(), "FeatureCategoryId", "Name", feature.FeatureCategoryId);
            ViewData["FeatureStatusId"] = new SelectList(_context.Set<FeatureStatus>(), "FeatureStatusId", "Name", feature.FeatureStatusId);
            ViewData["LastUpdateUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", feature.LastUpdateUserId);
            ViewData["ReporterUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", feature.ReporterUserId);

            return View(feature);
        }

        // GET: Features/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feature = await _context.Feature.FindAsync(id);

            if (feature == null)
            {
                return NotFound();
            }

            ViewData["AssigneeUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", feature.AssigneeUserId);
            ViewData["FeatureCategoryId"] = new SelectList(_context.Set<FeatureCategory>(), "FeatureCategoryId", "Name", feature.FeatureCategoryId);
            ViewData["FeatureStatusId"] = new SelectList(_context.Set<FeatureStatus>(), "FeatureStatusId", "Name", feature.FeatureStatusId);
            ViewData["LastUpdateUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", feature.LastUpdateUserId);
            ViewData["ReporterUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", feature.ReporterUserId);

            return View(feature);
        }

        // POST: Features/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FeatureId,ReporterUserId,AssigneeUserId,Title,Description,FeatureCategoryId,FeatureStatusId,CreationDate,UpdatedDate,LastUpdateUserId,Deleted")] Feature feature)
        {
            return await EditUtility(id, feature, false);
        }

        // GET: Features/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feature = await _context.Feature
                .Include(f => f.AssigneeUser)
                .Include(f => f.FeatureCategory)
                .Include(f => f.FeatureStatus)
                .Include(f => f.LastUpdateUser)
                .Include(f => f.ReporterUser)
                .FirstOrDefaultAsync(m => m.FeatureId == id);
            if (feature == null)
            {
                return NotFound();
            }

            return View(feature);
        }

        // POST: Features/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, [Bind("FeatureId,ReporterUserId,AssigneeUserId,Title,Description,FeatureCategoryId,FeatureStatusId,CreationDate,UpdatedDate,LastUpdateUserId,Deleted")] Feature feature)
        {
            return await EditUtility(id, feature, true);
        }

        private bool FeatureExists(int id)
        {
            return _context.Feature.Any(e => e.FeatureId == id);
        }

        private async Task<IActionResult> EditUtility(int id, [Bind("FeatureId,ReporterUserId,AssigneeUserId,Title,Description,FeatureCategoryId,FeatureStatusId,CreationDate,UpdatedDate,LastUpdateUserId,Deleted")] Feature feature, bool deleting)
        {
            if (id != feature.FeatureId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (deleting)
                        feature.Deleted = true;

                    feature.LastUpdateUserId = 1; // TODO change to current user
                    feature.UpdatedDate = DateTime.Now;

                    _context.Update(feature);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeatureExists(feature.FeatureId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AssigneeUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", feature.AssigneeUserId);
            ViewData["FeatureCategoryId"] = new SelectList(_context.Set<FeatureCategory>(), "FeatureCategoryId", "Name", feature.FeatureCategoryId);
            ViewData["FeatureStatusId"] = new SelectList(_context.Set<FeatureStatus>(), "FeatureStatusId", "Name", feature.FeatureStatusId);
            ViewData["LastUpdateUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", feature.LastUpdateUserId);
            ViewData["ReporterUserId"] = new SelectList(_context.Set<FeatureTrackerUser>(), "FeatureTrackerUserId", "FirstName", feature.ReporterUserId);
            return View(feature);
        }
    }
}

FeatureTracker/FeatureTracker/Controllers/UpdateLogsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FeatureTracker.Models;

namespace FeatureTracker.Controllers
{
    public class UpdateLogsController : Controller
    {
        private readonly FeatureTrackerContext _context;

        public UpdateLogsController(FeatureTrackerContext context)
        {
            _context = context;
        }

        // GET: Configuration/UpdateLogs
        [HttpGet("Configuration/UpdateLogs")]
        public async Task<IActionResult> Index()
        {
            var featureTrackerContext = _context.UpdateLog.Include(u => u.Action).Include(u => u.UpdatingUser);
            return View(await featureTrackerContext.ToListAsync());
        }
    }
}

FeatureTracker/FeatureTracker/Views/Shared/_BaseLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <partial name="_HeadScripts" />
</head>
<body>
    <partial name="_Header" />

    <div class="container body-content">
        @RenderBody()

        <partial name="_Footer" />
    </div>

    <partial name="_EnvironmentScripts" />
    @RenderSection("Scripts", required: false)
</body>
</html>

FeatureTracker/FeatureTracker/Views/Shared/_ConfigurationLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <partial name="_HeadScripts" />
</head>
<body>
    <partial name="_Header" />

    <div class="container body-content">

        <h2>Configuration</h2>

        <div class="row">
            <div class="col-md-3">
                <a asp-controller="FeatureCategories" asp-action="Index">
                    <div id="configurationFeatureCategories" class="configurationSelector">
                        FeatureCategories
                    </div>
                </a>
                <a asp-controller="FeatureStatus" asp-action="Index">
                    <div id="configurationFeatureStatuses" class="configurationSelector">
                        FeatureStatuses
                    </div>
                </a>
                <a asp-controller="FeatureTrackerUsers" asp-action="Index">
                    <div id="configurationUsers" class="configurationSelector">
                        Users
                    </div>
                </a>
                <a asp-controller="UpdateLogs" asp-action="Index">
                    <div id="configurationUpdateLog" class="configurationSelector">
                        Update Log
                    </div>
                </a>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>

        <partial name="_Footer" />
    </div>

    <partial name="_EnvironmentScripts" />
    @RenderSection("Scripts", required: false)
</body>
</html>

FeatureTracker/FeatureTracker/Views/Shared/_EnvironmentScripts.cshtml
<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@*@RenderSection("Scripts", required: false)*@

FeatureTracker/FeatureTracker/Views/Shared/_Footer.cshtml
<hr />
<footer>
    <p>&copy; 2018 - FeatureTracker</p>
</footer>

FeatureTracker/FeatureTracker/Views/Shared/_HeadScripts.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - Feature Tracker</title>

<environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</environment>

FeatureTracker/FeatureTracker/Views/Shared/_Header.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Features" asp-action="Index" class="navbar-brand">Feature Tracker</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Features" asp-action="Index">Features</a></li>
                <li><a asp-area="" asp-controller="Configuration" asp-action="Index">Configuration</a></li>
            </ul>
        </div>
    </div>
</nav>

@*<partial name="_CookieConsentPartial" />*@